### PR TITLE
fix(#14): return usable type name (in Name attr)

### LINKED ISSUE #14: [Bug]: Attribute Type returns all path to type
### Contact Details

_No response_

### What happened?

Exemple
```go
type Car struct {
	tires []Tire
}

type Tire struct{}
```
Will have it's `tires` `.Type` value equal to `github.com/Joffref/genz/examples/getters/test.Tire` in template
We only want "Tire".

### Version

beta

### Relevant log output

_No response_

### Template

_No response_

### Config

_No response_

### File

```shell
parser.go
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by leorolland**
Closes #14

### CODE REVIEW

File: internal/parser/types.go [hunk 1]
```diff
@@ -25,5 +25,7 @@ type (
 		Comments []string
 	}
 
-	Type string
+	Type struct {
+		Name string
```
Comment (leorolland) [inline internal/parser/types.go:29]: Why this change ?
- To be future proof when we add more attributes into Type function (and no breaking change)
- Because we could not use string helpers in template in a "Type" type (eg. `.Type | upper` was broken because .Type is not of type string)

File: internal/parser/parser.go [hunk 2]
```diff
@@ -132,3 +138,21 @@ func structMethods(namedType *types.Named) ([]Method, error) {
...
+
+	// Adds the package qualifier before the type name
+	// transforming "github.com/google/uuid.UUID" into "uuid.UUID"
+	relativeToExternalPackageQualifier := func(pkg *types.Package) string {
+		return pkg.Name()
+	}
+
+	return Type{
+		Name:         types.TypeString(t, relativeToExternalPackageQualifier), // (e.g. "uuid.UUID")
+		InternalName: types.TypeString(t, noPackageQualifier),                 // (e.g. "UUID")
```
Comment (leorolland) [inline internal/parser/parser.go:155]: InternalName is the variable to use when you generate Go code **inside** the scanned package.
Name is the variable to use when you generate Go code **outside** the scanned package

File: internal/parser/types.go [hunk 3]
```diff
@@ -25,5 +25,17 @@ type (
...
+		// Example `uuid.UUID` or `time.Time`
+		// Use this variable if you generate code outside the package of that type
+		// Do not forget to add corresponding imports in your template
+		Name string
+
+		// Name of the type from inside its package
+		// Example `UUID` or `Time`
+		// Use this variable if you generate code inside the package of that type
+		InternalName string
+	}
```
Comment (Joffref) [inline internal/parser/types.go:40]: IMO, it makes more sense to express Type as this. Then if you want to generate code outside of the package, you'll have to use: `{{.PackageName}}.{{Name}}`
```suggestion
	Type struct {

		// Name of the package the type belongs to
		// Example `uuid` or `time`
		// If you generate code outside this package do not forget to add corresponding imports in your template.
		// If needed
		PackageName string

		// Name of the type.
		// Example `UUID` or `Time`
	        Name string
	}
```

Comment (leorolland) [reply internal/parser/types.go:40]: Ok but how to you deal with types like 
`map[UUID]UUID` becoming `map[uuid.UUID]uuid.UUID` if expressed outside from the uuid package ?

Comment (leorolland) [reply internal/parser/types.go:40]: (also think about even more complex types, with structs.. and remember that the main use case is ''i want to get express the type being inside the PKG and outside, then I think two strings can cover 99% of our needs for now, we can enrich the struct later)

Comment (Joffref) [reply internal/parser/types.go:40]: It seems to be a problem outside of the scope of GenZ, let's use template helper or template functions to address that.

Comment (Joffref) [reply internal/parser/types.go:40]: I mean, let's keep type as it's expressed in the package seems to be sufficient enough at the moment

Comment (leorolland) [reply internal/parser/types.go:40]: > I mean, let's keep type as it's expressed in the package seems to be sufficient enough at the moment 

It's not sufficient at the moment, I want to generate some code types that are referenced from outside their package, for example google/uuid

Comment (Joffref) [reply internal/parser/types.go:40]: As discussed, this enhancement will come in future PR. Let's keep the current approach for the moment.

**Review by Joffref — APPROVED** [review]
LGTM
